DROP TABLE Player;
DROP TABLE Team;

CREATE TABLE Team (idTeam BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, name VARCHAR(20) NOT NULL,
 region VARCHAR(4) NOT NULL, dateOfEstablishment DATE);
 
CREATE TABLE Player (idPlayer BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, name VARCHAR(30) NOT NULL, 
surname VARCHAR(50) NOT NULL, ign VARCHAR(30) NOT NULL, role VARCHAR(10) NOT NULL, idTeam BIGINT FOREIGN KEY REFERENCES Team(idTeam),
 isRetired BOOLEAN DEFAULT FALSE);
 
INSERT INTO Team (NAME, REGION, DATEOFESTABLISHMENT) VALUES ('TSM', 'NA', '2011-01-01');
INSERT INTO Team (NAME, REGION, DATEOFESTABLISHMENT) VALUES ('Fnatic', 'EU', '2011-06-18');
INSERT INTO Team (NAME, REGION, DATEOFESTABLISHMENT) VALUES ('Roccat', 'PL', '2014-01-01');

INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Jason'   , 'Tran'    , 'Wildturtle', 'AD'     , 1, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Søren'   , 'Bjerg'   , 'Bjergsen'  , 'Mid'    , 1, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Lucas'   , 'Larsen'  , 'Santorin'  , 'Jungle' , 1, true);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Marcus'  , 'Hill'    , 'Dyrus'     , 'Top'    , 1, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Jang-sik', 'Jang-sik', 'Lustboy'   , 'Support', 1, true);

INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Heo'   , 'Seung-hoon' , 'Huni'      , 'Top'    , 2, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Kim'   , 'Ui-jin'     , 'Reignover' , 'Jungle' , 2, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Fabian', 'Diepstraten', 'Febiven'   , 'Mid'    , 2, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Martin', 'Larsson'    , 'Rekkles'   , 'AD'     , 2, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Bora'  , 'Kim'        , 'YellOwStaR', 'Support', 2, false);

INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Etienne', 'Michels'   , 'Steve'       , 'Top'   , 3, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Marcin' , 'Jankowski' , 'Jankos'      , 'Jungle', 3, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Erlend' , 'Holm'	    , 'Nukeduck'    , 'Mid'   , 3, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Rasmus' , 'Skinneholm', 'MrRalleZ'    , 'AD'    , 3, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Oskar'  , 'Bogdan'	, 'VandeR'      , 'Jungle', 3, false);
INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED) VALUES ('Jakob'  , 'Mebdi'	    , 'YamatoCannon', 'Coach' , 3, false);